<table class="table table-responsive" id="notasExtras-table">
    <thead>
        <tr>
        <th>No</th>
        <th>Estudiante</th>
        <th>Cedula</th>
        <th>Fecha_Reg</th>
        <th>Participación</th>
        <th>Examen_Enes</th>
        <th>2°</th>
        <th>3°</th>
        <th>4°</th>
        <th>5°</th>
        <th>6°</th>
        <th>7°</th>
        <th>Cert_Primaria</th>        
        <th>8°</th>
        <th>9°</th>
        <th>10°</th>
        <th>1°</th>
        <th>2°</th>
        <th>3°</th>
        <th>Obs</th>        
        <th>Action</th>
        </tr>
    </thead>
    <tbody>

    </tbody>
</table>